// Chinese lunar calendar / solar terms / festivals (table lookup, 2019-2100; table generated by preview/gen_lunar.py)
#pragma once
#include <stdint.h>

struct LunarDate { uint8_t month; bool leap; uint8_t day; int8_t term; };   // term: solar-term index 0-23 (Minor Cold = 0), -1 = none

bool  lunarFromSolar(int y, int m, int d, LunarDate& out);   // returns false outside the table range
const char* lunarMonthName(uint8_t month, bool leap);         // "正月" (first month) / "闰四月" (leap fourth month)
const char* lunarDayName(uint8_t day);                        // "初一" ... "三十" (day 1 ... day 30)
const char* lunarTermName(int8_t term);                       // "小寒" (Minor Cold) ...
// Second line of a calendar cell: festival > solar term > month name on the 1st > day name. Returns a static buffer
const char* lunarCellText(int y, int m, int d);
// Gregorian-calendar helpers
bool  isLeapYear(int y);
int   daysInMonth(int y, int m);
int   weekdayOf(int y, int m, int d);   // 0 = Sunday
