"""Generate lunar_tab.h (lunar calendar + solar-term table, 2020-2100) and lunar_expect.csv (per-day expected
values used to test lunar.cpp).
Usage: uvx --with lunar_python python gen_lunar.py <out_dir>"""
import sys, datetime
from lunar_python import Solar
Y0, Y1 = 2019, 2100
TERMS = ["小寒","大寒","立春","雨水","惊蛰","春分","清明","谷雨","立夏","小满","芒种","夏至","小暑","大暑","立秋","处暑","白露","秋分","寒露","霜降","立冬","小雪","大雪","冬至"]
out = sys.argv[1] if len(sys.argv) > 1 else "."
def lunar(d):
    l = Solar.fromYmd(d.year, d.month, d.day).getLunar()
    m = l.getMonth(); return l.getYear(), abs(m), m < 0, l.getDay(), l.getJieQi()
rows = []       # (uint32 packed) per year
terms = []      # 24 bytes per year
csv = []
for Y in range(Y0, Y1 + 1):
    # find the first day of the first lunar month of lunar year Y
    d = datetime.date(Y, 1, 15)
    while lunar(d)[:4] != (Y, 1, False, 1): d += datetime.timedelta(1)
    ny = d
    # walk to the next lunar new year, recording each month's length
    months = []   # (month, leap, days)
    cur = None; cnt = 0; leap = 0
    while True:
        ly, lm, ll, ld, _ = lunar(d)
        if (ly, lm, ll, ld) == (Y + 1, 1, False, 1): break
        key = (lm, ll)
        if key != cur:
            if cur: months.append((cur[0], cur[1], cnt))
            cur = key; cnt = 0
            if ll: leap = lm
        cnt += 1; d += datetime.timedelta(1)
    months.append((cur[0], cur[1], cnt))
    assert len(months) == (13 if leap else 12), (Y, months)
    bits = 0
    for i, (m, l, n) in enumerate(months):
        assert n in (29, 30); 
        if n == 30: bits |= 1 << i
    packed = bits | (leap << 13) | (ny.day << 17) | (ny.month << 22)
    rows.append(packed)
    # solar terms
    t = {}
    d = datetime.date(Y, 1, 1)
    while d.year == Y:
        jq = lunar(d)[4]
        if jq in TERMS: t[jq] = d.day
        d += datetime.timedelta(1)
    assert len(t) == 24, (Y, t)
    terms.append([t[n] for n in TERMS])
# per-day expectations: year,month,day,lmonth,leap,lday,termIndex(-1)
d = datetime.date(Y0, 1, 1)
while d.year <= Y1:
    ly, lm, ll, ld, jq = lunar(d)
    csv.append(f"{d.year},{d.month},{d.day},{lm},{int(ll)},{ld},{TERMS.index(jq) if jq in TERMS else -1}")
    d += datetime.timedelta(1)
with open(f"{out}/lunar_tab.h", "w") as f:
    f.write("// Generated by preview/gen_lunar.py using lunar_python; do not edit by hand. Lunar years 2020-2100:\n")
    f.write("// bit0-12 month lengths (1 = 30 days, leap month included in order), bit13-16 leap month (0 = none),\n"
            "// bit17-21 Gregorian day of lunar new year, bit22-25 its Gregorian month\n")
    f.write(f"#define LUNAR_YEAR0 {Y0}\n#define LUNAR_YEARS {Y1 - Y0 + 1}\n")
    f.write("static const uint32_t LUNAR_TAB[LUNAR_YEARS] PROGMEM = {\n")
    for i in range(0, len(rows), 8): f.write("  " + ", ".join(f"0x{v:08x}" for v in rows[i:i+8]) + ",\n")
    f.write("};\n// Day-of-month of the 24 solar terms, in order Minor Cold, Major Cold, Start of Spring ... Winter\n"
            "// Solstice (term i falls in Gregorian month i/2+1)\n")
    f.write("static const uint8_t TERM_TAB[LUNAR_YEARS][24] PROGMEM = {\n")
    for t in terms: f.write("  {" + ",".join(str(v) for v in t) + "},\n")
    f.write("};\n")
open(f"{out}/lunar_expect.csv", "w").write("\n".join(csv) + "\n")
print("years", len(rows), "days", len(csv))
