"""Render text with the u8g2 bitmap fonts the firmware compiles in, so the previews are pixel-identical to the device.

The fonts are read straight out of the C sources: fonts_noto.c (the 14/16/18 px Noto Sans CJK sets generated by
gen_fonts.sh) and U8g2's own u8g2_fonts.c (logisoso38_tn, the time font). No font files are needed beyond those.

    from u8g2font import fonts, Draw
    F = fonts()                       # {14: noto14, 16: noto16, 18: noto18, 38: logisoso38_tn}
    d = Draw(img)                     # drop-in for ImageDraw.Draw: text()/textlength() accept these fonts
    d.text((8, 42), "16:28", font=F[38], anchor="ls")

Baseline semantics follow u8g2: the y coordinate is the baseline, glyphs sit above it; a glyph missing from the
font draws nothing and advances 0 px (a blank on the preview means a blank on the device — extend charset.txt).
"""
import os, re, sys
from PIL import ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
U8G2_FONTS_C_CANDIDATES = [
    os.environ.get("U8G2_FONTS_C", ""),
    os.path.expanduser("~/arduino-user/libraries/U8g2_for_Adafruit_GFX/src/u8g2_fonts.c"),
    os.path.expanduser("~/Documents/Arduino/libraries/U8g2_for_Adafruit_GFX/src/u8g2_fonts.c"),
]

_ESC = {"n": 10, "t": 9, "r": 13, "a": 7, "b": 8, "f": 12, "v": 11, "\\": 92, '"': 34, "'": 39, "?": 63}

def _unescape(lit):
    """Bytes of a C string literal body (no surrounding quotes): octal/hex escapes, plus the simple ones."""
    out = bytearray(); i = 0; n = len(lit)
    while i < n:
        c = lit[i]
        if c != "\\": out.append(ord(c)); i += 1; continue
        i += 1; c = lit[i]
        if c in "01234567":
            j = i
            while j < n and j - i < 3 and lit[j] in "01234567": j += 1
            out.append(int(lit[i:j], 8) & 0xFF); i = j
        elif c == "x":
            j = i + 1
            while j < n and lit[j] in "0123456789abcdefABCDEF": j += 1
            out.append(int(lit[i+1:j], 16) & 0xFF); i = j
        else:
            out.append(_ESC[c]); i += 1
    return bytes(out)

def load_c_font(path, name):
    """Extract the byte array of `name` from a C file where it is stored as concatenated string literals."""
    with open(path, "rb") as fh: src = fh.read().decode("latin-1")
    m = re.search(r"\b" + re.escape(name) + r"\s*\[\s*\d*\s*\][^=;]*=\s*", src)
    if not m: raise KeyError(f"{name} not found in {path}")
    data = bytearray(); p = m.end()
    for lit in re.finditer(r'"((?:[^"\\]|\\.)*)"|;', src[p:]):
        if lit.group(0) == ";": break
        data += _unescape(lit.group(1))
    return bytes(data)

class _Bits:
    def __init__(self, data, pos): self.d = data; self.pos = pos; self.bit = 0
    def u(self, cnt):               # unsigned, LSB first, exactly like u8g2_font_decode_get_unsigned_bits
        val = self.d[self.pos] >> self.bit
        if self.bit + cnt >= 8:
            self.pos += 1
            if self.pos < len(self.d): val |= self.d[self.pos] << (8 - self.bit)
            self.bit = self.bit + cnt - 8
        else: self.bit += cnt
        return val & ((1 << cnt) - 1)
    def s(self, cnt): return self.u(cnt) - (1 << (cnt - 1))

class U8g2Font:
    HDR = 23
    def __init__(self, data, name=""):
        self.data = data; self.name = name; d = data
        (self.glyph_cnt, self.bbx_mode, self.bits_0, self.bits_1, self.bits_w, self.bits_h, self.bits_x, self.bits_y,
         self.bits_dx, self.max_w, self.max_h) = d[:11]
        self.ascent_A = _s8(d[13]); self.descent_g = _s8(d[14]); self.ascent_para = _s8(d[15]); self.descent_para = _s8(d[16])
        self._index = {}            # codepoint -> offset of the glyph bit data
        p = self.HDR
        while p + 1 < len(d) and d[p + 1] != 0:            # 8-bit encodings: [enc][len][bits...]
            self._index[d[p]] = p + 2; p += d[p + 1]
        upos = (d[21] << 8) | d[22]
        if upos:                                            # unicode block: jump table then [enc16][len][bits...]
            table = self.HDR + upos; p = table + ((d[table] << 8) | d[table + 1])
            while p + 2 < len(d):
                e = (d[p] << 8) | d[p + 1]
                if e == 0: break
                self._index[e] = p + 3; p += d[p + 2]
        self._cache = {}
        self._warned = set()

    def glyph(self, cp):
        """(w, h, xo, yo, dx, rows) with rows a list of ints (bit 1<<(w-1-col) set = ink); None if missing."""
        if cp in self._cache: return self._cache[cp]
        off = self._index.get(cp)
        if off is None: self._cache[cp] = None; return None
        b = _Bits(self.data, off)
        w = b.u(self.bits_w); h = b.u(self.bits_h); xo = b.s(self.bits_x); yo = b.s(self.bits_y); dx = b.s(self.bits_dx)
        rows = [0] * h
        if w > 0 and h > 0:
            x = y = 0
            def run(n, ink):
                nonlocal x, y
                while n > 0:
                    cnt = min(n, w - x)
                    if ink and y < h: rows[y] |= ((1 << cnt) - 1) << (w - x - cnt)
                    x += cnt; n -= cnt
                    if x >= w: x = 0; y += 1
            while True:
                a = b.u(self.bits_0); c = b.u(self.bits_1)
                while True:
                    run(a, False); run(c, True)
                    if b.u(1) == 0: break
                if y >= h: break
        g = (w, h, xo, yo, dx, rows); self._cache[cp] = g; return g

    def width(self, s):             # same as U8g2_for_Adafruit_GFX::getUTF8Width: sum of delta_x, 0 for missing glyphs
        return sum(g[4] for g in (self.glyph(ord(c)) for c in s) if g)

    def draw(self, img, x, y, s, fill=0):
        px = img.load(); W, H = img.size; x = int(x); y = int(y)
        for c in s:
            g = self.glyph(ord(c))
            if g is None:
                if c not in self._warned:
                    self._warned.add(c); print(f"u8g2font: '{c}' (U+{ord(c):04X}) is not in {self.name}", file=sys.stderr)
                continue
            w, h, xo, yo, dx, rows = g
            top = y - (h + yo); left = x + xo
            for r, bits in enumerate(rows):
                if not bits: continue
                yy = top + r
                if 0 <= yy < H:
                    for col in range(w):
                        if bits & (1 << (w - 1 - col)):
                            xx = left + col
                            if 0 <= xx < W: px[xx, yy] = fill
            x += dx

class Draw:
    """ImageDraw.Draw stand-in: text()/textlength() route U8g2Font instances to the bitmap renderer,
    everything else (lines, rectangles, PIL fonts) goes to the wrapped ImageDraw."""
    def __init__(self, img): self.img = img; self._d = ImageDraw.Draw(img)
    def __getattr__(self, n): return getattr(self._d, n)
    def textlength(self, s, font=None, **kw):
        if isinstance(font, U8g2Font): return font.width(s)
        return self._d.textlength(s, font=font, **kw)
    def text(self, xy, s, font=None, fill=0, anchor="ls", **kw):
        if not isinstance(font, U8g2Font): return self._d.text(xy, s, font=font, fill=fill, anchor=anchor, **kw)
        if anchor[1] != "s": raise ValueError("u8g2 fonts draw from the baseline only (anchor '?s')")
        x, y = xy; tw = font.width(s)
        if anchor[0] == "r": x -= tw                     # ui.cpp txtRight
        elif anchor[0] == "m": x -= tw // 2              # ui.cpp txtCenter (integer division)
        font.draw(self.img, x, y, s, fill)

def _s8(v): return v - 256 if v > 127 else v

_FONTS = None
def fonts():
    """{14: noto14, 16: noto16, 18: noto18, 38: logisoso38_tn} — exactly the sets ui.cpp binds to F_SM/F_TXT/F_NAME/F_TIME."""
    global _FONTS
    if _FONTS: return _FONTS
    noto = os.path.join(HERE, "..", "fonts_noto.c")
    F = {sz: U8g2Font(load_c_font(noto, f"u8g2_font_noto{sz}_hd"), f"noto{sz}") for sz in (14, 16, 18)}
    for p in U8G2_FONTS_C_CANDIDATES:
        if p and os.path.exists(p):
            F[38] = U8g2Font(load_c_font(p, "u8g2_font_logisoso38_tn"), "logisoso38_tn"); break
    else:
        raise FileNotFoundError("u8g2_fonts.c (U8g2_for_Adafruit_GFX) not found; set U8G2_FONTS_C=/path/to/u8g2_fonts.c")
    _FONTS = F; return F

if __name__ == "__main__":          # quick self-check: dump a few glyphs as ASCII art
    F = fonts()
    for sz, text in ((38, "07:"), (16, "周五"), (14, "更新")):
        f = F[sz]; print(f"{f.name}: glyphs={len(f._index)} ascent={f.ascent_A} descent={f.descent_g} width({text!r})={f.width(text)}")
        for c in text:
            g = f.glyph(ord(c)); w, h, xo, yo, dx, rows = g
            print(f"  {c!r} w={w} h={h} xo={xo} yo={yo} dx={dx}")
            for r in rows: print("   " + "".join("#" if r & (1 << (w - 1 - i)) else "." for i in range(w)))
